name: NFX Core - Windows MSVC

on:
  push:
    branches: [ main ]
    paths:
      - 'include/**'
      - 'src/**'
      - 'test/**'
      - 'samples/**'
      - 'benchmark/**'
      - 'CMakeLists.txt'
      - '.github/workflows/build-windows-msvc.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'include/**'
      - 'src/**'
      - 'test/**'
      - 'samples/**'
      - 'benchmark/**'
      - 'CMakeLists.txt'
      - '.github/workflows/build-windows-msvc.yml'

env:
  BUILD_TYPE: Release

jobs:
  build-windows:
    runs-on: windows-2022
    name: Windows MSVC 2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B build -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DNFX_CORE_BUILD_STATIC=ON -DNFX_CORE_BUILD_SHARED=OFF -DNFX_CORE_BUILD_TESTS=ON -DNFX_CORE_BUILD_SAMPLES=OFF -DNFX_CORE_BUILD_BENCHMARKS=OFF -DNFX_CORE_BUILD_DOCUMENTATION=OFF

    - name: Build
      run: cmake --build build --config ${{ env.BUILD_TYPE }} --parallel

    - name: Test
      working-directory: build
      run: ctest --output-on-failure --parallel

    - name: Archive build artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: nfx-core-windows-msvc-${{ github.sha }}
        path: |
          build/nfx-core-*/lib/
          build/nfx-core-*/bin/
          !build/**/CMakeFiles/
          !build/**/*.obj
          !build/**/*.o
          !build/**/*.pdb
          !build/**/*.exp
          !build/**/*.ilk
        retention-days: 30
