name: NFX Core - Windows MinGW

on:
  push:
    branches: [ main ]
    paths:
      - 'include/**'
      - 'src/**'
      - 'test/**'
      - 'samples/**'
      - 'benchmark/**'
      - 'CMakeLists.txt'
      - '.github/workflows/build-windows-mingw.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'include/**'
      - 'src/**'
      - 'test/**'
      - 'samples/**'
      - 'benchmark/**'
      - 'CMakeLists.txt'
      - '.github/workflows/build-windows-mingw.yml'

env:
  BUILD_TYPE: Release

jobs:
  build-windows-mingw:
    runs-on: windows-2022
    name: Windows MinGW

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Cache CMake build
      uses: actions/cache@v4
      with:
        path: |
          build
          D:\a\_temp\msys64\home\runneradmin\.cache\ccache
        key: ${{ runner.os }}-mingw-cmake-${{ hashFiles('**/CMakeLists.txt', 'include/**', 'src/**') }}
        restore-keys: |
          ${{ runner.os }}-mingw-cmake-

    - name: Set up MinGW
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-ccache

    - name: Setup ccache
      shell: msys2 {0}
      run: |
        export CCACHE_DIR="$HOME/.cache/ccache"
        export CCACHE_COMPILERCHECK=content
        export CCACHE_COMPRESS=true
        export CCACHE_MAXSIZE=200M
        ccache --zero-stats
        ccache --show-config

    - name: Configure CMake
      shell: msys2 {0}
      run: |
        export CC="ccache gcc"
        export CXX="ccache g++"
        export CCACHE_DIR="$HOME/.cache/ccache"
        cmake -B build \
              -G "Ninja" \
              -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
              -DNFX_CORE_BUILD_STATIC=ON \
              -DNFX_CORE_BUILD_SHARED=OFF \
              -DNFX_CORE_BUILD_TESTS=ON \
              -DNFX_CORE_BUILD_SAMPLES=OFF \
              -DNFX_CORE_BUILD_BENCHMARKS=OFF \
              -DNFX_CORE_BUILD_DOCUMENTATION=OFF

    - name: Build
      shell: msys2 {0}
      run: |
        export CCACHE_DIR="$HOME/.cache/ccache"
        cmake --build build --parallel

    - name: Test
      shell: msys2 {0}
      working-directory: build
      run: ctest --output-on-failure --parallel

    - name: Show ccache statistics
      shell: msys2 {0}
      run: ccache --show-stats
